# Bibliotecas necessárias

In [1]:
import sys
sys.path.append('/home/jovyan/work')
from datetime import datetime, timedelta
from crawler_sti import create_df
from utils.SendBuckets import SendBuckets

tabela = 'sti_atendimentos_sgt'
endpoint = 'https://apisgt.cni.org.br:8253/reports/v1.0.0/atendimentos'


import time
import pandas as pd

# Defina o número de dias que deseja iterar, incluindo o dia atual
num_dias = 10

# Data atual menos o número de dias, incluindo o dia atual
start_date = datetime.now() - timedelta(days=num_dias - 1)

In [2]:
#Bucket a ser gravado
send_buckets = SendBuckets('bronze')

# new

In [3]:
# Lista para armazenar os DataFrames
dfs = []

# Loop sobre os dias
for i in range(num_dias):
    # Calcula a data atual do loop
    current_date = start_date + timedelta(days=i)
    # Converte a data atual para o formato desejado ('YYYYMMDD')
    date_str = current_date.strftime('%Y%m%d')
    print('Data:', date_str)
    # Chama a função create_df() com a data atual
    df = create_df(endpoint, date_str, tabela, 'part')
    # Append do DataFrame à lista
    dfs.append(df)
    
    # Pausa de 10 segundos
    time.sleep(10)


# Concatenar os DataFrames da lista
final_df = pd.concat(dfs, ignore_index=True)

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Data: 20240401
DataFrame criado para sti_atendimentos_sgt na data 20240401
Data: 20240402

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DataFrame criado para sti_atendimentos_sgt na data 20240402
Data: 20240403

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DataFrame criado para sti_atendimentos_sgt na data 20240403
Data: 20240404

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DataFrame criado para sti_atendimentos_sgt na data 20240404
Data: 20240405

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DataFrame criado para sti_atendimentos_sgt na data 20240405
Data: 20240406

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Falha na carga da tabela sti_atendimentos_sgt: If using all scalar values, you must pass an index
Nenhum dado retornado ou DataFrame vazio para a data 20240406. Ignorando.
Data: 20240407

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Falha na carga da tabela sti_atendimentos_sgt: If using all scalar values, you must pass an index
Nenhum dado retornado ou DataFrame vazio para a data 20240407. Ignorando.
Data: 20240408

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Falha na carga da tabela sti_atendimentos_sgt: If using all scalar values, you must pass an index
Nenhum dado retornado ou DataFrame vazio para a data 20240408. Ignorando.
Data: 20240409

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Falha na carga da tabela sti_atendimentos_sgt: If using all scalar values, you must pass an index
Nenhum dado retornado ou DataFrame vazio para a data 20240409. Ignorando.
Data: 20240410

/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'apisgt.cni.org.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

DataFrame criado para sti_atendimentos_sgt na data 20240410

In [4]:
final_df

,id,idAtendimento,numeroAtendimento,tituloAtendimento,descricaoStatusAtendimento,dia,mes,ano,cpfCnpjCliente,nomeCliente,...,numeroDeProducaoEstimada,numeroDeRelatorioEstimado,numeroDeReceitaEstimada,vlrFinanceiro,vlrEconomico,isCompartilhado,isEmRede,isEscopoIndefinido,isValorHora,date_partition
0,1946915,249554,210951,IMEPP ENSAIOS DE CORPO DE PROVA,Concluído,1,4,2024,22039083000165,IMEPP INDUSTRIA MATERIAIS ELETRICOS POSTE E PA...,...,30,0,2660.1,0.0,0.0,false,false,false,false,2024-04-01
1,1946949,322145,220201,AZ INFORMATIC PDI,Concluído,1,4,2024,24598492000127,A Z INFORMATICA LTDA,...,336,0,67200.0,0.0,0.0,false,false,false,false,2024-04-01
2,1946943,330737,220368,EMHA CALIFORNIA CONSTRUCOES E INCORPORACOES SP...,Concluído,1,4,2024,36392885000169,EMHA CALIFORNIA CONSTRUCOES E INCORPORACOES SP...,...,1000,0,9000.0,0.0,0.0,false,false,false,false,2024-04-01
3,1946950,350943,220578,NEOVIA INFRAESTRUTURA RODOVIARIA LTDA,Concluído,1,4,2024,02955426000639,NEOVIA INFRAESTRUTURA RODOVIARIA LTDA,...,90,0,10800.0,0.0,0.0,false,false,false,false,2024-04-01
4,1946914,417342,230381,IMEPP INDUSTRIA MATERIAIS ELETRICOS POSTE E PA...,Concluído,1,4,2024,22039083000165,IMEPP INDUSTRIA MATERIAIS ELETRICOS POSTE E PA...,...,1921,0,19210.0,0.0,0.0,false,false,false,false,2024-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,1950455,541403,240528,SERVICO DE PESQUISA E INOVACAO INTELIGENCIA AR...,Em Prospecção (negociação),10,4,2024,04536786000117,J M D URBANISMO LTDA,...,1,0,99600.0,0.0,0.0,false,false,false,false,2024-04-10
141,1950547,541404,240529,SK MADEIRAS BP OPOR 004966 PROP 004327,Aceito/Contratado,10,4,2024,03642988000180,S.K. MADEIRAS EIRELI,...,1,0,20900.0,0.0,0.0,false,false,false,false,2024-04-10
142,1950549,541405,240530,ENSAIOS DE DESEMPENHO LUMINICO OPOR 004969 PRO...,Aceito/Contratado,10,4,2024,02245010000112,C M F CONSTRUCOES LTDA,...,1,0,900.0,0.0,0.0,false,false,false,false,2024-04-10
143,1950458,541406,240531,PROGRAMA BP LEIDE OPOR 004949 PROP 004312,Em Prospecção (negociação),10,4,2024,12309536000172,LEIDE INDUSTRIA E COMERCIO DE CONFECCOES EIRELI,...,1,0,15200.0,0.0,0.0,false,false,false,false,2024-04-10
144,1950459,541407,240532,PROGRAMA BP INOVE UNIFORMES OPOR 004950 PROP 0...,Em Prospecção (negociação),10,4,2024,25302760000184,S. C. M. VIEIRA INDUSTRIA E COMERCIO DE UNIFOR...,...,1,0,20900.0,0.0,0.0,false,false,false,false,2024-04-10

In [6]:
final_df_selected = final_df[final_df['dia'] == '06']
final_df_selected

Empty DataFrame
Columns: [id, idAtendimento, numeroAtendimento, tituloAtendimento, descricaoStatusAtendimento, dia, mes, ano, cpfCnpjCliente, nomeCliente, idPorteCliente, porteCliente, numeroDeFuncionarios, descricaoProdutoRegional, CRProdutoRegional, codigoDNProdutoNacional, descricaoProdutoNacional, codigoDNProdutoCategoria, descricaoProdutoCategoria, codigoDNProdutoLinha, descricaoProdutoLinha, codigoOBAUnidadeOperacional, descricaoUnidadeOperacional, numeroDeProducaoEstimada, numeroDeRelatorioEstimado, numeroDeReceitaEstimada, vlrFinanceiro, vlrEconomico, isCompartilhado, isEmRede, isEscopoIndefinido, isValorHora, date_partition]
Index: []

[0 rows x 33 columns]

In [8]:
send_buckets.send_dataframe_bucket_part('overwrite', f'sti/apisgt/{tabela}', final_df, 'date_partition')

Salvando localmente em pasta temporária
Removendo arquivos em sti/apisgt/sti_atendimentos_sgt/date_partition=20240410
Removendo arquivos em sti/apisgt/sti_atendimentos_sgt/date_partition=20240409
Removendo arquivos em sti/apisgt/sti_atendimentos_sgt/date_partition=20240406
Removendo arquivos em sti/apisgt/sti_atendimentos_sgt/date_partition=20240407
Removendo arquivos em sti/apisgt/sti_atendimentos_sgt/date_partition=20240408
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240407/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240407/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240409/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240409/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240410/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240410/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240408/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240408/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240408/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240408/part-00001-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet
Enviando arquivo /tmp/tmp_refined_72lcp3px/date_partition=20240406/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet para o MinIO em sti/apisgt/sti_atendimentos_sgt/date_partition=20240406/part-00000-18a21b29-1e2d-424c-a99f-5239c90ea35d.c000.snappy.parquet